### ISSUE TITLE
Deleting everything

### ISSUE THREAD

**Issue by distributorofpain** [burnettk/delete-docker-registry-image#23]
I went through and deleted all the docker images in my registry but after checking the file structure, there are still a bunch of files in the blob directory that don't seem to be tied to anything.  I am wondering if i can just delete those, perhaps they are orphans?  The problem is the orphan files take up around 27 GB of space and i need the space back.  the files taking up space are all called "data".

**Comment by burnettk** [comment]
Hey Brent,

There are unit tests for various scenarios along these lines. There are some cases where files stick around. A pull request with a failing test and fix is welcome. :)

Otherwise, I'm a bit loathe to advise you to delete data without knowing your precise use case, but if you're just trying to trash all the images in your registry, probably rm -rf everything is your friend.

**Comment by distributorofpain** [comment]
I think i will delete everything using your script, then rm -f on the blob directory to clear out the clutter.  The devs can re-upload everything.  I may end up rebuilding the VM due to the space limitation anyhow :disappointed: 

Thanks for the input, i will consider it going forward should this become a thing with the devs..
